name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: List files in the app directory
        run: ls -la ./App  # Adjust this path if needed

     
      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./App  # Adjust this if package.json is in a different directory

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}  # Region should be passed here

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REPOSITORY: demo_app_ecr_repo  # Replace with your ECR repo name
          IMAGE_TAG: ${{ github.sha }}

        run: |
          # Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./App
          # Tag the image for ECR
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          # Push the image to ECR
          docker push ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
