name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REPOSITORY: demo_app_ecr_repo  # Replace with your ECR repo name
          AWS_REGION: us-east-1              # Replace with your region
          IMAGE_TAG: ${{ github.sha }}

        run: |
          docker login -u AWS -p ${{ secrets.AWS_ECR_PASSWORD }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          # Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          # Tag the image for ECR
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          # Push the image to ECR
          docker push ${{ steps.ecr-login.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
